//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda_usuario
    {
        public int id_agenda { get; set; }
        public int id_usuario { get; set; }
        public int id_presentacion { get; set; }
        public Nullable<bool> recordatorio { get; set; }
        public Nullable<System.DateTime> fecha_agregado { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual presentaciones presentaciones { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
