//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ciudades()
        {
            this.venues = new HashSet<venues>();
        }
    
        public int id_ciudad { get; set; }
        public int id_pais { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual paises paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venues> venues { get; set; }
    }
}
