//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public compras()
        {
            this.pagos = new HashSet<pagos>();
            this.reembolsos = new HashSet<reembolsos>();
        }
    
        public int id_compra { get; set; }
        public int id_usuario { get; set; }
        public int id_tipo_ticket { get; set; }
        public Nullable<int> id_descuento { get; set; }
        public string codigo_orden { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public Nullable<decimal> total { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual descuentos descuentos { get; set; }
        public virtual tipos_ticket tipos_ticket { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagos> pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reembolsos> reembolsos { get; set; }
    }
}
