//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTickets
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_ticketsEntities : DbContext
    {
        public gestion_ticketsEntities()
            : base("name=gestion_ticketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agenda_usuario> agenda_usuario { get; set; }
        public virtual DbSet<artistas> artistas { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<ciudades> ciudades { get; set; }
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<conversion_moneda> conversion_moneda { get; set; }
        public virtual DbSet<descuentos> descuentos { get; set; }
        public virtual DbSet<eventos> eventos { get; set; }
        public virtual DbSet<fotos_venue> fotos_venue { get; set; }
        public virtual DbSet<likes> likes { get; set; }
        public virtual DbSet<metodos_pago_cash> metodos_pago_cash { get; set; }
        public virtual DbSet<metodos_pago_tarjeta> metodos_pago_tarjeta { get; set; }
        public virtual DbSet<metodos_pago_transferencia> metodos_pago_transferencia { get; set; }
        public virtual DbSet<notificaciones> notificaciones { get; set; }
        public virtual DbSet<pagos> pagos { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<presentaciones> presentaciones { get; set; }
        public virtual DbSet<reembolsos> reembolsos { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<secciones_venue> secciones_venue { get; set; }
        public virtual DbSet<tipos_ticket> tipos_ticket { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<usuarios_rol> usuarios_rol { get; set; }
        public virtual DbSet<venues> venues { get; set; }
    }
}
