//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pagos()
        {
            this.reembolsos = new HashSet<reembolsos>();
        }
    
        public int id_pago { get; set; }
        public int id_compra { get; set; }
        public int id_usuario { get; set; }
        public string metodo { get; set; }
        public Nullable<int> id_metodo_tarjeta { get; set; }
        public Nullable<int> id_metodo_transferencia { get; set; }
        public Nullable<int> id_metodo_cash { get; set; }
        public decimal monto { get; set; }
        public string moneda { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual compras compras { get; set; }
        public virtual metodos_pago_cash metodos_pago_cash { get; set; }
        public virtual metodos_pago_tarjeta metodos_pago_tarjeta { get; set; }
        public virtual metodos_pago_transferencia metodos_pago_transferencia { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reembolsos> reembolsos { get; set; }
    }
}
