//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class presentaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public presentaciones()
        {
            this.agenda_usuario = new HashSet<agenda_usuario>();
            this.likes = new HashSet<likes>();
        }
    
        public int id_presentacion { get; set; }
        public int id_evento { get; set; }
        public int id_artista { get; set; }
        public string escenario { get; set; }
        public System.DateTime fecha_hora_inicio { get; set; }
        public Nullable<System.DateTime> fecha_hora_fin { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda_usuario> agenda_usuario { get; set; }
        public virtual artistas artistas { get; set; }
        public virtual eventos eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<likes> likes { get; set; }
    }
}
