//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class reembolsos
    {
        public int id_reembolso { get; set; }
        public int id_compra { get; set; }
        public int id_pago { get; set; }
        public decimal monto { get; set; }
        public string motivo { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_proceso { get; set; }
    
        public virtual compras compras { get; set; }
        public virtual pagos pagos { get; set; }
    }
}
