//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class secciones_venue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public secciones_venue()
        {
            this.tipos_ticket = new HashSet<tipos_ticket>();
        }
    
        public int id_seccion { get; set; }
        public int id_venue { get; set; }
        public string nombre { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual venues venues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipos_ticket> tipos_ticket { get; set; }
    }
}
