//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipos_ticket()
        {
            this.compras = new HashSet<compras>();
        }
    
        public int id_tipo_ticket { get; set; }
        public int id_evento { get; set; }
        public Nullable<int> id_seccion { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public string moneda { get; set; }
        public int cantidad_ticket { get; set; }
        public Nullable<System.DateTime> venta_inicio { get; set; }
        public Nullable<System.DateTime> venta_fin { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compras> compras { get; set; }
        public virtual eventos eventos { get; set; }
        public virtual secciones_venue secciones_venue { get; set; }
    }
}
